//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatatableTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatatableTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.DatatableTexts", typeof(DatatableTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou žádné záznamy.
        /// </summary>
        public static string emptyTable {
            get {
                return ResourceManager.GetString("emptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazeno _START_ do _END_ z _TOTAL_ záznamů.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou žádné záznamy.
        /// </summary>
        public static string infoEmpty {
            get {
                return ResourceManager.GetString("infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtrováno z _MAX_ maximálního počtu záznamů).
        /// </summary>
        public static string infoFiltered {
            get {
                return ResourceManager.GetString("infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string infoPostFix {
            get {
                return ResourceManager.GetString("infoPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit _MENU_ záznamů.
        /// </summary>
        public static string lengthMenu {
            get {
                return ResourceManager.GetString("lengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načítám....
        /// </summary>
        public static string loadingRecords {
            get {
                return ResourceManager.GetString("loadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to První.
        /// </summary>
        public static string paginate_first {
            get {
                return ResourceManager.GetString("paginate_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední.
        /// </summary>
        public static string paginate_last {
            get {
                return ResourceManager.GetString("paginate_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další.
        /// </summary>
        public static string paginate_next {
            get {
                return ResourceManager.GetString("paginate_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předchozí.
        /// </summary>
        public static string paginate_previous {
            get {
                return ResourceManager.GetString("paginate_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načítám....
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat:.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string thousands {
            get {
                return ResourceManager.GetString("thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádná shoda.
        /// </summary>
        public static string zeroRecords {
            get {
                return ResourceManager.GetString("zeroRecords", resourceCulture);
            }
        }
    }
}
