//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LopTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LopTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.LopTexts", typeof(LopTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bylo odmítnuto řešení podúkolu.
        /// </summary>
        public static string ByloOdmitnutoReseniPodukolu {
            get {
                return ResourceManager.GetString("ByloOdmitnutoReseniPodukolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bylo odmítnuto řešení úkolu.
        /// </summary>
        public static string ByloOdmitnutoReseniUkolu {
            get {
                return ResourceManager.GetString("ByloOdmitnutoReseniUkolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bylo přijato řešení úkolu.
        /// </summary>
        public static string ByloPrijatoReseniLopu {
            get {
                return ResourceManager.GetString("ByloPrijatoReseniLopu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bylo přijato řešení podúkolu.
        /// </summary>
        public static string ByloPrijatoReseniPodukolu {
            get {
                return ResourceManager.GetString("ByloPrijatoReseniPodukolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byl upraven úkol.
        /// </summary>
        public static string BylUpravenLop {
            get {
                return ResourceManager.GetString("BylUpravenLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byl Vám přidělen nový podúkol.
        /// </summary>
        public static string BylVamPridelenNovyPodukol {
            get {
                return ResourceManager.GetString("BylVamPridelenNovyPodukol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byl Vám přidělen nový úkol.
        /// </summary>
        public static string BylVamPridelenNovyUkol {
            get {
                return ResourceManager.GetString("BylVamPridelenNovyUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem podúkolů.
        /// </summary>
        public static string CelkemSubukolu {
            get {
                return ResourceManager.GetString("CelkemSubukolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkové procentuální vyřešení úkolu.
        /// </summary>
        public static string CelkoveVyreseniUkolu {
            get {
                return ResourceManager.GetString("CelkoveVyreseniUkolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kontroly (zadavatelem).
        /// </summary>
        public static string CheckDate {
            get {
                return ResourceManager.GetString("CheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum uzavření (řešitelem).
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dílna.
        /// </summary>
        public static string Dilna {
            get {
                return ResourceManager.GetString("Dilna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo k neočekávané chybě.
        /// </summary>
        public static string DosloKNeocekavaneChybe {
            get {
                return ResourceManager.GetString("DosloKNeocekavaneChybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit podúkol.
        /// </summary>
        public static string EditSubUkol {
            get {
                return ResourceManager.GetString("EditSubUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum ukončení (zadavatelem).
        /// </summary>
        public static string FinishDate {
            get {
                return ResourceManager.GetString("FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotové úkoly.
        /// </summary>
        public static string HotoveLopy {
            get {
                return ResourceManager.GetString("HotoveLopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotové podúkoly.
        /// </summary>
        public static string HotoveSubukoly {
            get {
                return ResourceManager.GetString("HotoveSubukoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotové úkoly.
        /// </summary>
        public static string HotoveUkoly {
            get {
                return ResourceManager.GetString("HotoveUkoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investice.
        /// </summary>
        public static string Investice {
            get {
                return ResourceManager.GetString("Investice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Jmeno {
            get {
                return ResourceManager.GetString("Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentář.
        /// </summary>
        public static string Komentar {
            get {
                return ResourceManager.GetString("Komentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední změna.
        /// </summary>
        public static string LastChangedDate {
            get {
                return ResourceManager.GetString("LastChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda podbarvení řádků.
        /// </summary>
        public static string LegendaPodbarveni {
            get {
                return ResourceManager.GetString("LegendaPodbarveni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Learned.
        /// </summary>
        public static string LessonLearned {
            get {
                return ResourceManager.GetString("LessonLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam úkolů.
        /// </summary>
        public static string ListLop {
            get {
                return ResourceManager.GetString("ListLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam smazaných úkolů.
        /// </summary>
        public static string ListLopDeleted {
            get {
                return ResourceManager.GetString("ListLopDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam úkolů detailně.
        /// </summary>
        public static string ListLopsDetailed {
            get {
                return ResourceManager.GetString("ListLopsDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail úkolu.
        /// </summary>
        public static string LopDetail {
            get {
                return ResourceManager.GetString("LopDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol úspěšně aktualizován.
        /// </summary>
        public static string LopUspesneAktualizovan {
            get {
                return ResourceManager.GetString("LopUspesneAktualizovan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkoly ke kontrole.
        /// </summary>
        public static string LopyKeKontrole {
            get {
                return ResourceManager.GetString("LopyKeKontrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiál.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druh.
        /// </summary>
        public static string MaterialDruh {
            get {
                return ResourceManager.GetString("MaterialDruh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sap číslo.
        /// </summary>
        public static string MaterialSapCislo {
            get {
                return ResourceManager.GetString("MaterialSapCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sap popis.
        /// </summary>
        public static string MaterialSapPopis {
            get {
                return ResourceManager.GetString("MaterialSapPopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejzašší plánované ukončení.
        /// </summary>
        public static string MaxPlannedCloseDate {
            get {
                return ResourceManager.GetString("MaxPlannedCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string Nazev {
            get {
                return ResourceManager.GetString("Nazev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyl přidán produkt.
        /// </summary>
        public static string NebylPridanProdukt {
            get {
                return ResourceManager.GetString("NebylPridanProdukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyly provedeny žádné změny.
        /// </summary>
        public static string NebylyProvedenyZadneZmeny {
            get {
                return ResourceManager.GetString("NebylyProvedenyZadneZmeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nechci se podílet na řešení.
        /// </summary>
        public static string NechciSePodiletNaReseni {
            get {
                return ResourceManager.GetString("NechciSePodiletNaReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze ukončit úkol, některé podúkoly.
        /// </summary>
        public static string NelzeUkoncitUkol1 {
            get {
                return ResourceManager.GetString("NelzeUkoncitUkol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je ještě potřeba vyřešit.
        /// </summary>
        public static string NelzeUkoncitUkol2 {
            get {
                return ResourceManager.GetString("NelzeUkoncitUkol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se odmítnout podúkol.
        /// </summary>
        public static string NepodariloSeOdmitnoutPodukol {
            get {
                return ResourceManager.GetString("NepodariloSeOdmitnoutPodukol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se odmítnout úkol.
        /// </summary>
        public static string NepodariloSeOdmitnoutUkol {
            get {
                return ResourceManager.GetString("NepodariloSeOdmitnoutUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se připojení produktů k úkolu.
        /// </summary>
        public static string NepodariloSePripojeniProduktuKUkolu {
            get {
                return ResourceManager.GetString("NepodariloSePripojeniProduktuKUkolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se upravit záznam.
        /// </summary>
        public static string NepodariloSeUpravitZaznam {
            get {
                return ResourceManager.GetString("NepodariloSeUpravitZaznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesplněné úkoly.
        /// </summary>
        public static string NesplneneLopy {
            get {
                return ResourceManager.GetString("NesplneneLopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesplněné podúkoly.
        /// </summary>
        public static string NesplneneSubukoly {
            get {
                return ResourceManager.GetString("NesplneneSubukoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesplněné úkoly.
        /// </summary>
        public static string NesplneneUkoly {
            get {
                return ResourceManager.GetString("NesplneneUkoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové oddělení.
        /// </summary>
        public static string NoveOddeleni {
            get {
                return ResourceManager.GetString("NoveOddeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový úkol.
        /// </summary>
        public static string NovyLop {
            get {
                return ResourceManager.GetString("NovyLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový podúkol.
        /// </summary>
        public static string NovySubUkol {
            get {
                return ResourceManager.GetString("NovySubUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový úkol.
        /// </summary>
        public static string NovyUkol {
            get {
                return ResourceManager.GetString("NovyUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový úsek.
        /// </summary>
        public static string NovyUsek {
            get {
                return ResourceManager.GetString("NovyUsek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddělení.
        /// </summary>
        public static string Oddeleni {
            get {
                return ResourceManager.GetString("Oddeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odmítl řešit podúkol.
        /// </summary>
        public static string OdmitlResitPodukol {
            get {
                return ResourceManager.GetString("OdmitlResitPodukol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odmítl řešit úkol.
        /// </summary>
        public static string OdmitlResitUkol {
            get {
                return ResourceManager.GetString("OdmitlResitUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odmítnout řešení.
        /// </summary>
        public static string OdmitnoutReseni {
            get {
                return ResourceManager.GetString("OdmitnoutReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odmítnuto řešitelem.
        /// </summary>
        public static string Odmitnuto {
            get {
                return ResourceManager.GetString("Odmitnuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operace.
        /// </summary>
        public static string Operace {
            get {
                return ResourceManager.GetString("Operace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizace.
        /// </summary>
        public static string Organizace {
            get {
                return ResourceManager.GetString("Organizace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označit jako nevyřešený.
        /// </summary>
        public static string OznacitNevyreseny {
            get {
                return ResourceManager.GetString("OznacitNevyreseny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označit jako vyřešený.
        /// </summary>
        public static string OznacitVyreseny {
            get {
                return ResourceManager.GetString("OznacitVyreseny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánované datum ukončení.
        /// </summary>
        public static string PlannedCloseDate {
            get {
                return ResourceManager.GetString("PlannedCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plán. datum ukončení.
        /// </summary>
        public static string PlannedCloseDateShort {
            get {
                return ResourceManager.GetString("PlannedCloseDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkol byl odmítnut.
        /// </summary>
        public static string PodukolBylOdmitnut {
            get {
                return ResourceManager.GetString("PodukolBylOdmitnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkol byl označen jako vyřešený.
        /// </summary>
        public static string PodukolBylOznacenJakoVyreseny {
            get {
                return ResourceManager.GetString("PodukolBylOznacenJakoVyreseny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkol byl vyřešen.
        /// </summary>
        public static string PodukolBylVyresen {
            get {
                return ResourceManager.GetString("PodukolBylVyresen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkol je znovu v řešení.
        /// </summary>
        public static string PodukolJeZnovuVReseni {
            get {
                return ResourceManager.GetString("PodukolJeZnovuVReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkol přidaný.
        /// </summary>
        public static string PodukolPridany {
            get {
                return ResourceManager.GetString("PodukolPridany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkol smazán.
        /// </summary>
        public static string PodukolSmazan {
            get {
                return ResourceManager.GetString("PodukolSmazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string Popis {
            get {
                return ResourceManager.GetString("Popis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslat upozornění řešiteli.
        /// </summary>
        public static string PoslatUpozorneniResiteli {
            get {
                return ResourceManager.GetString("PoslatUpozorneniResiteli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslat upozornění zadavateli.
        /// </summary>
        public static string PoslatUpozorneniZadavateli {
            get {
                return ResourceManager.GetString("PoslatUpozorneniZadavateli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdit.
        /// </summary>
        public static string Potvrdit {
            get {
                return ResourceManager.GetString("Potvrdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Poznamka {
            get {
                return ResourceManager.GetString("Poznamka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled podúkolů.
        /// </summary>
        public static string PrehledPodukolu {
            get {
                return ResourceManager.GetString("PrehledPodukolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat dílnu uživateli.
        /// </summary>
        public static string PridatDilnuUzivateli {
            get {
                return ResourceManager.GetString("PridatDilnuUzivateli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat existujícího zaměstnance.
        /// </summary>
        public static string PridatExistujicihoZamestnance {
            get {
                return ResourceManager.GetString("PridatExistujicihoZamestnance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat existující oddělení.
        /// </summary>
        public static string PridatExistujiciOddeleni {
            get {
                return ResourceManager.GetString("PridatExistujiciOddeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat podúkol.
        /// </summary>
        public static string PridatPodukol {
            get {
                return ResourceManager.GetString("PridatPodukol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přijmout řešení.
        /// </summary>
        public static string PrijmoutReseni {
            get {
                return ResourceManager.GetString("PrijmoutReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procentuální stavy subúkolů v lopu.
        /// </summary>
        public static string ProcentualniStavySubukolu {
            get {
                return ResourceManager.GetString("ProcentualniStavySubukolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Produkt {
            get {
                return ResourceManager.GetString("Produkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provázané produkty.
        /// </summary>
        public static string ProduktyVazane {
            get {
                return ResourceManager.GetString("ProduktyVazane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provázané materiály byly aktualizovány.
        /// </summary>
        public static string ProvazaneMaterialyBylyAktualizovany {
            get {
                return ResourceManager.GetString("ProvazaneMaterialyBylyAktualizovany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provedené změny.
        /// </summary>
        public static string ProvedeneZmeny {
            get {
                return ResourceManager.GetString("ProvedeneZmeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Původní hodnoty.
        /// </summary>
        public static string PuvodniHodnoty {
            get {
                return ResourceManager.GetString("PuvodniHodnoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Řešitel.
        /// </summary>
        public static string Resitel {
            get {
                return ResourceManager.GetString("Resitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam úkolů.
        /// </summary>
        public static string SeznamUkolu {
            get {
                return ResourceManager.GetString("SeznamUkolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam úkolů oddělení.
        /// </summary>
        public static string SeznamUkoluOddeleni {
            get {
                return ResourceManager.GetString("SeznamUkoluOddeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam úkolů vedení.
        /// </summary>
        public static string SeznamUkoluVedeni {
            get {
                return ResourceManager.GetString("SeznamUkoluVedeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam úkolů vzorkování.
        /// </summary>
        public static string SeznamUkoluVzorkovani {
            get {
                return ResourceManager.GetString("SeznamUkoluVzorkovani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zahájení.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkol.
        /// </summary>
        public static string SubUkol {
            get {
                return ResourceManager.GetString("SubUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail podúkolu.
        /// </summary>
        public static string SubUkolDetail {
            get {
                return ResourceManager.GetString("SubUkolDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkoly.
        /// </summary>
        public static string SubUkoly {
            get {
                return ResourceManager.GetString("SubUkoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúkoly ke kontrole.
        /// </summary>
        public static string SubukolyKeKontrole {
            get {
                return ResourceManager.GetString("SubukolyKeKontrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol byl odmítnut.
        /// </summary>
        public static string UkolBylOdmitnut {
            get {
                return ResourceManager.GetString("UkolBylOdmitnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol byl označen jako vyřešený.
        /// </summary>
        public static string UkolBylOznacenJakoVyreseny {
            get {
                return ResourceManager.GetString("UkolBylOznacenJakoVyreseny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol byl vyřešen.
        /// </summary>
        public static string UkolBylVyresen {
            get {
                return ResourceManager.GetString("UkolBylVyresen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol je znovu v řešení.
        /// </summary>
        public static string UkolJeZnovuVReseni {
            get {
                return ResourceManager.GetString("UkolJeZnovuVReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol oddělení.
        /// </summary>
        public static string UkolOddeleni {
            get {
                return ResourceManager.GetString("UkolOddeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deatil úkolu oddělení.
        /// </summary>
        public static string UkolOddeleniDetail {
            get {
                return ResourceManager.GetString("UkolOddeleniDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol přidaný.
        /// </summary>
        public static string UkolPridany {
            get {
                return ResourceManager.GetString("UkolPridany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol smazán.
        /// </summary>
        public static string UkolSmazan {
            get {
                return ResourceManager.GetString("UkolSmazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol vedení.
        /// </summary>
        public static string UkolVedeni {
            get {
                return ResourceManager.GetString("UkolVedeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deatil úkolu vedení.
        /// </summary>
        public static string UkolVedeniDetail {
            get {
                return ResourceManager.GetString("UkolVedeniDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol vzorkování.
        /// </summary>
        public static string UkolVzorkovani {
            get {
                return ResourceManager.GetString("UkolVzorkovani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deatil úkolu vzorkování.
        /// </summary>
        public static string UkolVzorkovaniDeatil {
            get {
                return ResourceManager.GetString("UkolVzorkovaniDeatil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkoly ke kontrole.
        /// </summary>
        public static string UkolyKeKontrole {
            get {
                return ResourceManager.GetString("UkolyKeKontrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string Upravit {
            get {
                return ResourceManager.GetString("Upravit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit oddělení.
        /// </summary>
        public static string UpravitOddeleni {
            get {
                return ResourceManager.GetString("UpravitOddeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit podúkol.
        /// </summary>
        public static string UpravitPodukol {
            get {
                return ResourceManager.GetString("UpravitPodukol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit úkol.
        /// </summary>
        public static string UpravitUkol {
            get {
                return ResourceManager.GetString("UpravitUkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit úsek.
        /// </summary>
        public static string UpravitUsek {
            get {
                return ResourceManager.GetString("UpravitUsek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úsek.
        /// </summary>
        public static string Usek {
            get {
                return ResourceManager.GetString("Usek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelé.
        /// </summary>
        public static string Uzivatele {
            get {
                return ResourceManager.GetString("Uzivatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš komentář.
        /// </summary>
        public static string VasKomentar {
            get {
                return ResourceManager.GetString("VasKomentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedoucí.
        /// </summary>
        public static string Vedouci {
            get {
                return ResourceManager.GetString("Vedouci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedoucí oddělení.
        /// </summary>
        public static string VedouciOddeleni {
            get {
                return ResourceManager.GetString("VedouciOddeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedoucí úseku.
        /// </summary>
        public static string VedouciUseku {
            get {
                return ResourceManager.GetString("VedouciUseku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výběr úseku.
        /// </summary>
        public static string VyberUseku {
            get {
                return ResourceManager.GetString("VyberUseku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výběr vedoucího.
        /// </summary>
        public static string VyberVedouciho {
            get {
                return ResourceManager.GetString("VyberVedouciho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat produkty.
        /// </summary>
        public static string VybratProdukty {
            get {
                return ResourceManager.GetString("VybratProdukty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadavatel.
        /// </summary>
        public static string Zadavatel {
            get {
                return ResourceManager.GetString("Zadavatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string Zavrit {
            get {
                return ResourceManager.GetString("Zavrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkontrolovat řešení.
        /// </summary>
        public static string ZkontrolovatReseni {
            get {
                return ResourceManager.GetString("ZkontrolovatReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkontrolujte zadané údaje.
        /// </summary>
        public static string ZkontrolujteZadaneUdaje {
            get {
                return ResourceManager.GetString("ZkontrolujteZadaneUdaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změněné položky.
        /// </summary>
        public static string ZmenenePolozky {
            get {
                return ResourceManager.GetString("ZmenenePolozky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnil.
        /// </summary>
        public static string Zmenil {
            get {
                return ResourceManager.GetString("Zmenil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit.
        /// </summary>
        public static string Zmenit {
            get {
                return ResourceManager.GetString("Zmenit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změny úspěšně uloženy.
        /// </summary>
        public static string ZmenyUspesneUlozeny {
            get {
                return ResourceManager.GetString("ZmenyUspesneUlozeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zobrazit méně.
        /// </summary>
        public static string ZobrazitMene {
            get {
                return ResourceManager.GetString("ZobrazitMene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zobrazit více.
        /// </summary>
        public static string ZobrazitVice {
            get {
                return ResourceManager.GetString("ZobrazitVice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit aktuální úkoly.
        /// </summary>
        public static string ZobrazPuvodni {
            get {
                return ResourceManager.GetString("ZobrazPuvodni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit smazané úkoly.
        /// </summary>
        public static string ZobrazSmazane {
            get {
                return ResourceManager.GetString("ZobrazSmazane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string Zpet {
            get {
                return ResourceManager.GetString("Zpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na detail.
        /// </summary>
        public static string ZpetNaLopDetail {
            get {
                return ResourceManager.GetString("ZpetNaLopDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na výpis.
        /// </summary>
        public static string ZpetNaVypis {
            get {
                return ResourceManager.GetString("ZpetNaVypis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string Zrusit {
            get {
                return ResourceManager.GetString("Zrusit", resourceCulture);
            }
        }
    }
}
